apiVersion: v1
kind: Pod
metadata:
  name: supermario-pod
  labels:
    app: mario
spec:
  containers:
    - name: supermario-demo
      image: pengbai/docker-supermario
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
